---
output: html_document
editor_options: 
  chunk_output_type: console
---
# NEW tasks {#Newtasks}

## Create tasks

There are a number of elements the tasks need to work well with jsPsychR, so we recommend to use one of the systems we have developed.

For example, with `create_protocol()`, you can create new tasks as part of a fully working protocol to be able to test them using `csv` or `xls/xlxs` files for the items and html files for the instructions.  

There are some things to take into account:   

- The **tasks_folder** expects a folder with sub-folders with the ShortName of tasks. Inside, they need to have one `csv` or `xls/xlxs` file and `html` files  

- The **csv or xls/xlsx file** (ShortName.csv or Shortname.xls/xlsx) needs to have an `ID` and `plugin` columns, and then columns by the name of parameters used in the plugin (e.g. if using the `survey-text` plugin, you will need the `prompt` parameter). If you need **help with the plugins parametes**, see [the jsPsych 6.3 list of plugins](https://www.jspsych.org/6.3/plugins/list-of-plugins/)    

- For each **html file** (ShortName_instructions.html, ShortName_instructions2.html, etc) an instructions page will be created. The files need to end with `_instructions.html` or `instructions#.html` (# is a number). If there is no html, a default page will be used  

- For **key questions** (e.g. present this question only if participants responded "3"), you need to create a column named `if_question` and include a logical condition. For example:

  + `1 != 25`: Response to item 1 is NOT 25
  + `3 == 20`: Response to item 3 is 20
  + `15 == yes`: Response to item 3 is yes


You can run the fully reproducible example included in jsPsychMaker. It uses the files from `admin/example_tasks_new_protocol/`.  

---  

`create_protocol()` will:

- Loop through the subfolders in `tasks_folder` to create one task per subfolder
- Copy `canonical_protocol clean` to `folder_output`
- Modify `config.js` to add the recently created tasks
- Modify `index.html` to add only the plugins those tasks will use
- Check task names are OK (no spaces, _, -, do not start by a number, ...)
- Check only one csv or xls/xlsx file per folder
- Check plugins used exist in jsPsych-6/plugins


---  

```{r, eval=FALSE}

# Download jsPsychMaker. This will open a new RStudio project called "gorkang-jsPsychMaker-..."
if (!require('usethis')) install.packages('usethis'); library('usethis')
usethis::use_course("gorkang/jsPsychMaker")


# Launch these two commands in the new RStudio project (gorkang-jsPsychMaker-...)
invisible(lapply(list.files("./R", full.names = TRUE, pattern = ".R$"), source))
create_protocol(tasks_folder = "admin/example_tasks_new_protocol/", 
                folder_output = "admin/OUTPUT/NEW", 
                launch_browser = TRUE)

```



## Help with new tasks {#HelpNewtasks}
If you need help developing new tasks, you can [open a new Issue in the jsPsychMaker Github](https://github.com/gorkang/jsPsychMaker/issues).

We will ask you to add the details about the task in the [NEW tasks document](https://docs.google.com/spreadsheets/d/1LAsyTZ2ZRP_xLiUBkqmawwnKWgy8OCwq4mmWrrc_rpQ/edit#gid=0).

Once the task is implemented, our goal is to always end up having a sister task preparation script in [jsPsychHelpeR](https://github.com/gorkang/jsPsychHelpeR). You can try [to create the preparation script](#create-new-tasks) and do a Pull request, or ask for help [opening a new Issue in the jsPsychHelpeR Github](https://github.com/gorkang/jsPsychHelpeR/issues).


## How to fill the NEW tasks document

---  

[NEW tasks document](https://docs.google.com/spreadsheets/d/1LAsyTZ2ZRP_xLiUBkqmawwnKWgy8OCwq4mmWrrc_rpQ/edit#gid=0)  

---  

First of all, you will need the original paper where the task was validated/translated to have all the details at hand. Please, send us a link to the paper.  

The best way to fill the [NEW tasks document](https://docs.google.com/spreadsheets/d/1LAsyTZ2ZRP_xLiUBkqmawwnKWgy8OCwq4mmWrrc_rpQ/edit#gid=0) is:  

1. Find a task similar to yours in the document [Tareas jsPsychR](https://docs.google.com/spreadsheets/d/1Eo0F4GcmqWZ1cghTpQlA4aHsc8kTABss-HAeimE2IqA/edit#gid=0) where we have information about all the available tasks.  

2. Copy/paste the information from all the tabs to the [NEW tasks document](https://docs.google.com/spreadsheets/d/1LAsyTZ2ZRP_xLiUBkqmawwnKWgy8OCwq4mmWrrc_rpQ/edit#gid=0) and adapt it.  



Try to be as consistent as possible. For example, when entering the information about numeric conversion in the Puntajes_items tab:

    All the cells must be:  
    1 = Mucho  
    2 = Poco  
    ...

DO NOT do things like:

    1: Mucho  
    1 Mucho  
    1 pto = Mucho  
    Mucho 1  

Please, make sure you fill out all the details in all the tabs.
