# Common Tasks {#CommonTasks}


## Install dependencies

```{r, eval=FALSE}

# if (!require('renv')) utils::install.packages('renv'); renv::install("gorkang/jsPsychAdmin")

```



## Developing a protocol

### Creating a protocol

```{r, eval=FALSE}

# if (!require('renv')) utils::install.packages('renv'); renv::install("gorkang/jsPsychMaker")

```


### Adding new tasks


```{r, eval=FALSE}

# TODO

```


### Piloting the protocol

```{r, eval=FALSE}

# if (!require('renv')) utils::install.packages('renv'); renv::install('gorkang/jsPsychMonkeys')

jsPsychMonkeys::release_the_monkeys(uid = "1:100",
                    sequential_parallel = "parallel",
                    number_of_cores = 10,
                    server_folder_tasks = "test/protocols_DEV/999",
                    DEBUG = FALSE,
                    credentials_folder = "/home/emrys/gorkang@gmail.com/RESEARCH/PROYECTOS-Code/jsPsychR/jsPsychMonkeys/.vault/", 
                    open_VNC = FALSE)

```



### Deleting pilot data

```{r, eval=FALSE}

    # Delete the XYZ protocol rows in all the MYSQL tables
    source("admin/mysql_helper_functions.R")
    # list_credentials = decrypt_data(key_public = readLines(".vault/data_public_key.txt"), data_encrypted = ".vault/data_encrypted.rds", mysupersecretpassword = rstudioapi::askForPassword())
    delete_MySQL_tables_pid(pid)
    
  
  # 3) Limpiar los archivos de resultados de Monkeys -----------------------
    
    # Delete csv files in .data/
    # rstudioapi::navigateToFile(".vault/.credentials") 
    DELETE_data_server(pid = PROTOCOLID)
    
```


### Preparing Helper project


#### Get data {#GetData}

Will download a zip file with the data.  

```{r, eval=FALSE}

# if (!require('renv')) utils::install.packages('renv'); renv::install('gorkang/jsPsychHelpeR')

# Developing protocol
jsPsychHelpeR::get_zip(pid = "test/protocols_DEV/31", what = "data",  where = "data/")

# Production protocol
jsPsychHelpeR::get_zip(pid = "999", what = "data",  where = "data/")


```

### Prepare new task correction project

```{r, eval=FALSE}

  jsPsychHelpeR::run_initial_setup(pid = 999,
                                   download_files = TRUE,
                                   folder = "~/Downloads/jsPsychR_MYPROJECT")

```


## Protocol to production

From `admin/000_PREPARE_protocol_for_production.R` in jsPsychAdmin

```{r, eval=FALSE}

# Checklist para pasar protocolos de test/protocols_DEV/ a produccion

  # PARAMETERS --------------------------------

  PROTOCOLID = "test/protocols_DEV/31"
  number_of_monkeys = "1:100"

  # -------------------------------------------

  # Automatic parameters
  pid = gsub("test/protocols_DEV/", "", PROTOCOLID)


   cli::cli_h1("PROTOCOL {pid}")


  # 1) Pilotaje final on Monkeys! -------------------------------------------

  # Clean data and MySQL DB
  # rstudioapi::navigateToFile(".vault/.credentials")
  jsPsychAdmin::clean_up_dev_protocol(protocol_id = PROTOCOLID) # Will ask for server password


  # LAUNCH MONKEYS
  jsPsychMonkeys::release_the_monkeys(uid = number_of_monkeys,
                                      server_folder_tasks = PROTOCOLID,
                                      sequential_parallel = "parallel",
                                      number_of_cores = 10,
                                      big_container = TRUE,
                                      keep_alive = FALSE, open_VNC = FALSE, screenshot = FALSE,
                                      credentials_folder = here::here(".vault/"))


  # CHECK jsPsychHelpeR runs OK

  # || THIS WILL take a while, as all the renv packages need to update
  # Create NEW jsPsychHelpeR project, downloading the files from the server
  jsPsychHelpeR::run_initial_setup(pid = PROTOCOLID,
                                   download_files = TRUE,
                                   folder = "~/Downloads/jsPsychR_TESTING_for_PRODUCTION")

    # REMEMBER TO DO targets::tar_make() in jsPsychHelpeR project!


  # 2) Clean data and  MySQL DB --------------------------------------------

    # rstudioapi::navigateToFile(".vault/.credentials")
    jsPsychAdmin::clean_up_dev_protocol(protocol_id = pid) # Will ask for server password


  # 3) Revisar el config.js para pasar el experiment a produccion ----------

    # -[] online = true
    # -[] pid OK?
    # -[] debug_mode = false
    # - ETC...


  # 4) Copiar protocolo ZIPeado a test/protocols_DEV/OLD_TESTS/ -------------

    # TODO: automatico!

  # 5) Copiar protocolo a protocols/ ----------------------------------------

    # TODO: automatico!

  # 6) BORRAR protocolo de test/protocols_DEV/OLD_TESTS/ --------------------

    # TODO: automatico!



```



