# jsPsychMonkeys {#jsPsychMonkeys}

[jsPsychMonkeys](https://github.com/gorkang/jsPsychMonkeys): Release monkeys to a jsPsych experiment using the R package {targets}, docker and {RSelenium}.


## Como simular datos

El sistema para simular participantes utiliza [Selenium](https://www.selenium.dev/) dentro de un contenedor de [Docker](https://www.docker.com/). En Linux es trivial su uso, pero en Windows su configuración puede ser más compleja.  

Puedes seguir los siguientes pasos, pero si no tienes una instalación funcional de Docker que utilice contenedores Linux, el sistema fallará. En ese caso, quedan las siguientes opciones:

- Correr un par de participantes manualmente  
- Usar un ordenador con Linux o crear una partición Linux  
- Crear una máquina virtual linux desde la que simular participantes. Puedes usar [Virtualbox](https://www.virtualbox.org/wiki/Downloads) para instalar [Ubuntu](https://releases.ubuntu.com/20.04/). Una vez dentro, tendrás que seguir los pasos del [manual para prepara el sistema para correr R y RStudio](https://gorkang.github.io/R_preparacion_visualizacion_datos/preparando-sistema.html#empezando-en-a-b-c)  

<!-- sudo apt install libssl-dev libcurl4-openssl-dev libxml2-dev  -->



---  

1) [Solo Windows] Descargamos e instalamos docker:

  https://docs.docker.com/docker-for-windows/install/  [~ 500MB]  
  
---  

  
2) Descargamos el proyecto de RStudio jsPsychMonkeys:  

```{r, eval=FALSE}

if (!require('usethis')) install.packages('usethis'); library('usethis')

usethis::use_course(url = "gorkang/jsPsychMonkeys", destdir = "~/Downloads/")
# Select YES to delete zip

```

---  

3) Abrimos `run.R` y seguimos las instrucciones.  


