project:
  type: book
  output-dir: docs
  # execute-dir: project

book:
  google-analytics: "G-WTTG1W9SNG"
  title: "jsPsychR manual"
  author: "Gorka Navarrete"
  date: today
  search: true
  url: https://gorkang.github.io/jsPsychRmanual/
  doi: 10.5281/zenodo.8296995
  repo-url: https://github.com/gorkang/jsPsychRmanual/
  downloads: [pdf]
  chapters:
    - index.qmd
    - qmd/01-intro.qmd
    - qmd/02-QuickGuide.qmd
    - qmd/03-jsPsychMaker.qmd
    - qmd/04-jsPsychMonkeys.qmd
    - qmd/05-jsPsychHelpeR.qmd
    - qmd/06-jsPsychRadmins.qmd
    - qmd/07-NEWtasks.qmd
    - qmd/08-CreateSimulatePrepare.qmd
    - qmd/09-CommonTasks.qmd
    - qmd/10-references.qmd

bibliography: [references.bib, tasks.bib, grateful-refs.bib]

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

